FROM tensorflow/tensorflow:1.14.0-gpu-jupyter
RUN mkdir -p app
WORKDIR /tf/app
COPY . .
RUN pip install scipy scikit-learn PyYAML matplotlib keras==2.3.0 pandas typing
EXPOSE 8888/tcp

ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN chmod +x /usr/bin/tini

ENV PYTHONPATH "${PYTHONPATH}:/tf/app"

ENTRYPOINT ["/usr/bin/tini", "--"]

CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]
